name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
      - uses: ohpensource/generate-version-and-release-notes-gh-action@v1.0.2
        name: semver & changelog
        with:
          user-email: "github-actions@github.com"
          user-name: "github-actions"
          version-prefix: "v"
      - uses: terraform-docs/gh-actions@v1.0.0
        name: Render terraform docs
        with:
          working-dir: .
          git-commit-message: "[tfm-docs][skip ci] - updating terraform docs"
          output-file: README.md
          output-method: inject
          git-push: "true"
