name: continuous-integration
on:
  pull_request:
    branches: [main]

jobs:

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ohpensource/ensure-conventional-commits-gh-action@v0.1.5
        name: Ensure conventional commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

  jira-tickets-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ohpensource/ensure-commits-have-ticket-gh-action@v0.1.1
        name: Ensure Jira ticket in all commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ohpensource/terraform-validate-gh-action/action@0.0.0.1
        name: validate-terraform
        with:
          terraform-folder: "./"
          use-backend: "false"

  validate-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/tfsec-action@v1.0.2
        name: analyse-security
