name: continuous-integration
on:
  pull_request:
    branches: [main]

jobs:

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ohpensource/ensure-conventional-commits-gh-action@v0.1.5
        name: Ensure conventional commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

  jira-tickets-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ohpensource/ensure-commits-have-ticket@v0.0.4
        name: Ensure Jira ticket in all commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.3
        with:
          files: "README.md"
      - name: ensure-documentation-is-added
        if: steps.changed-files.outputs.any_modified == 'false'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Include documentation in the README.md file!')

  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ohpensource/platform-cicd/actions/terraform/tfm-validate@2.15.0.1
        name: validate-terraform
        with:
          terraform-folder: "./"
          use-backend: "false"

  validate-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/tfsec-action@v1.0.2
        name: analyse-security

  tfm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          git-commit-message: "[tfm-docs][skip ci] - updating terraform docs"
          output-file: README.md
          output-method: inject
          git-push: "true"
